export const placementDrives: PlacementDrive[] = [
  {
    id: "tcs-nqt-2026",
    company: "TCS",
    examName: "TCS NQT 2026",
    date: "2026-06-15T10:00:00+05:30",
    logo: "tcs.com",
    eligibility: "B.Tech/BCA/MCA — 60%+ aggregate, no active backlogs",
    packageRange: "₹3.36 – ₹7 LPA",
    requiredReadiness: 350,
    category: "service",
    description: "National Qualifier Test — aptitude + coding + verbal. Gateway to TCS Digital and Ninja roles."
  },
  {
    id: "infosys-infytq-2026",
    company: "Infosys",
    examName: "InfyTQ Certification 2026",
    date: "2026-06-22T09:00:00+05:30",
    logo: "infosys.com",
    eligibility: "B.Tech/BE — 60%+ in 10th, 12th, and graduation",
    packageRange: "₹3.6 – ₹9.5 LPA",
    requiredReadiness: 380,
    category: "service",
    description: "InfyTQ certification followed by Infosys SP/DSE hiring. Python and Java focused."
  },
  {
    id: "wipro-nlth-2026",
    company: "Wipro",
    examName: "NLTH 2026",
    date: "2026-07-05T10:00:00+05:30",
    logo: "wipro.com",
    eligibility: "B.Tech/BCA/MCA — 60%+ aggregate",
    packageRange: "₹3.5 – ₹6.5 LPA",
    requiredReadiness: 330,
    category: "service",
    description: "National Level Talent Hunt. Aptitude + technical MCQ + coding round."
  },
  {
    id: "cognizant-genc-2026",
    company: "Cognizant",
    examName: "GenC Hiring 2026",
    date: "2026-07-12T10:00:00+05:30",
    logo: "cognizant.com",
    eligibility: "B.Tech/BE — 60%+ aggregate",
    packageRange: "₹4 – ₹8 LPA",
    requiredReadiness: 360,
    category: "service",
    description: "GenC and GenC Next roles. Automata Fix + coding challenge."
  },
  {
    id: "accenture-2026",
    company: "Accenture",
    examName: "Accenture Off-Campus 2026",
    date: "2026-07-20T09:30:00+05:30",
    logo: "accenture.com",
    eligibility: "B.Tech/BE/MCA — 60%+ aggregate, no current backlogs",
    packageRange: "₹4.5 – ₹11 LPA",
    requiredReadiness: 400,
    category: "service",
    description: "ASE and ACE roles. Cognitive + technical + coding assessment."
  },
  {
    id: "amazon-sde1-2026",
    company: "Amazon",
    examName: "SDE-1 Hiring 2026",
    date: "2026-08-10T10:00:00+05:30",
    logo: "amazon.com",
    eligibility: "B.Tech/MS — strong DSA and system design skills required",
    packageRange: "₹26 – ₹45 LPA",
    requiredReadiness: 720,
    category: "faang",
    description: "Online assessment (2 coding) → Phone screen → 4-round onsite (LP + coding + design)."
  },
  {
    id: "flipkart-sde1-2026",
    company: "Flipkart",
    examName: "SDE-1 Campus 2026",
    date: "2026-08-18T10:00:00+05:30",
    logo: "flipkart.com",
    eligibility: "B.Tech from top-tier colleges, CGPA 7.5+",
    packageRange: "₹22 – ₹38 LPA",
    requiredReadiness: 700,
    category: "product",
    description: "Coding test → Machine coding → 2 DS/Algo rounds → HM round."
  },
  {
    id: "google-swe-2026",
    company: "Google",
    examName: "SWE Intern/FTE 2026",
    date: "2026-09-01T10:00:00+05:30",
    logo: "google.com",
    eligibility: "B.Tech/MS from any college — strong competitive programming background",
    packageRange: "₹35 – ₹60 LPA",
    requiredReadiness: 800,
    category: "faang",
    description: "Online coding → 4-5 phone/onsite rounds. Heavy DSA + Googleyness."
  },
  {
    id: "microsoft-sde-2026",
    company: "Microsoft",
    examName: "SDE Campus 2026",
    date: "2026-08-25T10:00:00+05:30",
    logo: "microsoft.com",
    eligibility: "B.Tech/MS — CGPA 7.0+ preferred",
    packageRange: "₹30 – ₹52 LPA",
    requiredReadiness: 750,
    category: "faang",
    description: "Online test → Group fly → 3 technical + 1 HR round."
  },
  {
    id: "paytm-2026",
    company: "Paytm",
    examName: "SDE Hiring 2026",
    date: "2026-08-05T10:00:00+05:30",
    logo: "paytm.com",
    eligibility: "B.Tech — strong in DSA, DBMS, OS",
    packageRange: "₹14 – ₹22 LPA",
    requiredReadiness: 600,
    category: "product",
    description: "Coding test → 2 tech rounds → HR. Focus on DSA and system basics."
  },
  {
    id: "swiggy-sde-2026",
    company: "Swiggy",
    examName: "SDE-1 2026",
    date: "2026-08-28T10:00:00+05:30",
    logo: "swiggy.com",
    eligibility: "B.Tech — competitive programming + backend experience preferred",
    packageRange: "₹18 – ₹30 LPA",
    requiredReadiness: 650,
    category: "product",
    description: "Online round → Machine coding → 2 DS/Algo → System design → HR."
  },
  {
    id: "hcl-2026",
    company: "HCL",
    examName: "HCL TechBee / FTE 2026",
    date: "2026-07-28T10:00:00+05:30",
    logo: "hcltech.com",
    eligibility: "B.Tech/BCA — 60%+ aggregate",
    packageRange: "₹3.5 – ₹6 LPA",
    requiredReadiness: 320,
    category: "service",
    description: "Aptitude → Technical MCQ → Coding → Interview. Java/Python focus."
  },
  {
    id: "techmahindra-2026",
    company: "Tech Mahindra",
    examName: "Campus Hiring 2026",
    date: "2026-07-15T10:00:00+05:30",
    logo: "techmahindra.com",
    eligibility: "B.Tech/BE/MCA — 60%+ aggregate",
    packageRange: "₹3.25 – ₹5.5 LPA",
    requiredReadiness: 310,
    category: "service",
    description: "Online test + essay + technical + HR round."
  },
  {
    id: "zomato-sde-2026",
    company: "Zomato",
    examName: "SDE-1 2026",
    date: "2026-09-10T10:00:00+05:30",
    logo: "zomato.com",
    eligibility: "B.Tech — strong DSA + system design",
    packageRange: "₹16 – ₹28 LPA",
    requiredReadiness: 640,
    category: "product",
    description: "Coding challenge → 2 algo rounds → system design → culture fit."
  },
];
